### PR TITLE
add contenthash options

### PR DESCRIPTION
**Pull request by lcxfs1991**
We may need content hash for copied files too.

I run the tests and it shows the new feature does not affect old feature.

However, I don't have time to write a test for this feature, would u please write it for me?

Thank u so much!

### CODE REVIEW

**Comment by ksmithbaylor** [comment]
I'd also love to see this feature implemented, and would be willing to help out.

**Comment by kevlened** [comment]
Sorry for the delay on this. After some investigation, it seems that `loader-utils` has this functionality built in with `interpolateName`. I wasn't aware of loader-utils before this PR, so thanks! The master branch (not yet released) has template support.

**Comment by evilebottnawi** [comment]
@kevlened be good release with new versions in package.json

**Comment by kevlened** [comment]
This is now supported in version 4.0.0, and published to npm. Thanks again!

**Comment by lcxfs1991** [comment]
@kevlened can't locate the details in README. Haven't been updated?

**Comment by kevlened** [comment]
It's under https://github.com/kevlened/copy-webpack-plugin#usage. If you're looking for all the template options (including hash), the details of every template we support is here: https://github.com/webpack/file-loader#filename-template-placeholders

There's no `[contenthash]`, but `[hash]` should be what you need

**Pull request closed without merging**
